# Generated by Django 3.0.5 on 2021-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_withdraw_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='cashwithdraw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
