# Generated by Django 3.0.5 on 2021-09-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210829_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
